=== akemery/NoSQL-cours/nomprenom.dtd
<!-- schema.dtd-->
<!ELEMENT personnes (personne+) >
<!ELEMENT personne (nom, prenom, age?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== akemery/NoSQL-cours/nomprenomdtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personnes SYSTEM "nomprenom.dtd">
<personnes>
    <personne>
        <nom>OTCHOUNl</nom>
        <prenom>Rone</prenom>
    </personne>
    <personne>
        <nom>GNAMMI</nom>
        <prenom>Carine</prenom>
        <age>40</age>
    </personne>
</personnes>
